language: smalltalk

os: osx
osx_image: xcode7.3 # use macOS 10.11

smalltalk:
  - Squeak-trunk
  - Squeak-trunk-64 # experimental
  - Squeak-5.1
  - Squeak-5.1-64 # experimental
  - Squeak-5.0

  - Etoys-trunk-64
  - Etoys-trunk

matrix:
  allow_failures:
    # - smalltalk: Squeak-trunk-64
    # - smalltalk: Squeak-5.1-64
    - smalltalk: Squeak-5.0 # currently broken due to a stale test
    - smalltalk: Etoys-trunk-64
    - smalltalk: Etoys-trunk

script: ./prepare.sh

notifications:
  slack:
    rooms:
      - squeak:ID1VVfPsB1X17YiDK9F1VUcS#trunk
    template:
      - "Build <%{build_url}|#%{build_number}> of <https://github.com/squeak-smalltalk/squeak-app|squeak-app> %{result} in %{duration}"
    on_success: change
    on_failure: always
