language: smalltalk
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_c86f51260a97_key -iv $encrypted_c86f51260a97_iv
  -in certs/dist.zip.enc -out certs/dist.zip -d
script: ./prepare.sh
