language: smalltalk

os: osx
osx_image: xcode7.3 # use macOS 10.11

smalltalk:
  - Squeak-5.1
  - Squeak64-5.1

script: ./prepare.sh

notifications:
  slack:
    rooms:
      - squeak:ID1VVfPsB1X17YiDK9F1VUcS#trunk
    template:
      - "Build <%{build_url}|#%{build_number}> of <https://github.com/squeak-smalltalk/squeak-app|squeak-app> %{result} in %{duration}"
    on_success: change
    on_failure: always
